In [1]:
import numpy as np
import tensorflow as tf
from PIL import Image

tf.__version__

'2.1.0'

In [2]:
converter = tf.lite.TFLiteConverter.from_saved_model("nils_model_final")
tflite_model = converter.convert()
open("nils_model_converted.tflite", "wb").write(tflite_model)

476292

In [7]:
# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="nils_model_converted.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
#input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
img = Image.open("2020-06-16_09-03-18-946785.jpg")
img = np.array(img)
img = img.astype(np.float32)
img = np.expand_dims(img, axis=0)
interpreter.set_tensor(input_details[0]['index'], img)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

[[0.45000753]]


In [4]:
img

array([[[[161., 155., 143.],
         [150., 140., 130.],
         [139., 125., 114.],
         ...,
         [213., 212., 210.],
         [213., 212., 210.],
         [213., 212., 210.]],

        [[165., 157., 146.],
         [152., 142., 132.],
         [137., 127., 117.],
         ...,
         [213., 213., 211.],
         [213., 213., 211.],
         [215., 214., 210.]],

        [[172., 162., 152.],
         [159., 150., 141.],
         [139., 132., 124.],
         ...,
         [214., 214., 212.],
         [217., 217., 215.],
         [217., 218., 213.]],

        ...,

        [[174., 169., 189.],
         [175., 170., 190.],
         [175., 170., 190.],
         ...,
         [148., 144., 169.],
         [146., 142., 167.],
         [147., 143., 168.]],

        [[174., 170., 187.],
         [177., 169., 190.],
         [177., 169., 192.],
         ...,
         [147., 143., 168.],
         [149., 145., 170.],
         [146., 144., 168.]],

        [[174., 172., 186.],
       

In [68]:
a = [[1,2]]

In [69]:
a[0]

[1, 2]

In [48]:
input_tensor = interpreter.tensor(tensor_index)()[0]

In [60]:
b = input_tensor[:,:]

In [61]:
b.shape

(150, 150, 3)

In [62]:
b

array([[[0.9751294 , 0.25434104, 0.8153441 ],
        [0.28489518, 0.86479354, 0.29289916],
        [0.62251896, 0.60672915, 0.6001335 ],
        ...,
        [0.43394017, 0.02408455, 0.43955067],
        [0.04012147, 0.2972554 , 0.5934291 ],
        [0.72994953, 0.8255122 , 0.5253233 ]],

       [[0.96140754, 0.29578257, 0.56712854],
        [0.2481641 , 0.95636535, 0.4821553 ],
        [0.56829774, 0.80933374, 0.6534303 ],
        ...,
        [0.94321054, 0.71360284, 0.5769304 ],
        [0.5021673 , 0.91621995, 0.5710691 ],
        [0.29242328, 0.9429569 , 0.11705913]],

       [[0.94981796, 0.3624832 , 0.07393711],
        [0.14818643, 0.00881343, 0.1705345 ],
        [0.4063883 , 0.213592  , 0.38765252],
        ...,
        [0.70559067, 0.17757684, 0.06029443],
        [0.24611285, 0.05711827, 0.61062944],
        [0.65661865, 0.8274233 , 0.16691326]],

       ...,

       [[0.850799  , 0.9954056 , 0.99599046],
        [0.45082438, 0.5859028 , 0.7522018 ],
        [0.69869465, 0

In [63]:
a.shape

(1, 150, 150, 3)

In [64]:
b = np.expand_dims(b, axis=0)
b.shape

(1, 150, 150, 3)

In [66]:
b

array([[[[0.9751294 , 0.25434104, 0.8153441 ],
         [0.28489518, 0.86479354, 0.29289916],
         [0.62251896, 0.60672915, 0.6001335 ],
         ...,
         [0.43394017, 0.02408455, 0.43955067],
         [0.04012147, 0.2972554 , 0.5934291 ],
         [0.72994953, 0.8255122 , 0.5253233 ]],

        [[0.96140754, 0.29578257, 0.56712854],
         [0.2481641 , 0.95636535, 0.4821553 ],
         [0.56829774, 0.80933374, 0.6534303 ],
         ...,
         [0.94321054, 0.71360284, 0.5769304 ],
         [0.5021673 , 0.91621995, 0.5710691 ],
         [0.29242328, 0.9429569 , 0.11705913]],

        [[0.94981796, 0.3624832 , 0.07393711],
         [0.14818643, 0.00881343, 0.1705345 ],
         [0.4063883 , 0.213592  , 0.38765252],
         ...,
         [0.70559067, 0.17757684, 0.06029443],
         [0.24611285, 0.05711827, 0.61062944],
         [0.65661865, 0.8274233 , 0.16691326]],

        ...,

        [[0.850799  , 0.9954056 , 0.99599046],
         [0.45082438, 0.5859028 , 0.7522018 ]